;(load "C:\\WorkSpace\\Artificial Intelligence\\HW1\\6\\test-case.lisp")
(load "C:\\WorkSpace\\Artificial Intelligence\\HW1\\6\\family-tree2.lisp")

(terpri)
(princ "**** test-case parents ****")
(print (spouse *family-tree2* 'o))
(print (siblings *family-tree2* 'c))
(print (siblings *family-tree2* 'v))
(print (siblings *family-tree2* 'r))
(print (siblings *family-tree2* 'n))
(print (siblings *family-tree2* 'a))
(print (children *family-tree2* 'b))
(print (children *family-tree2* 'v))
(print (grandchildren *family-tree2* 'a))
(print (grandchildren *family-tree2* 'b))
(print (grandchildren *family-tree2* 'w))
(print (grandchildren *family-tree2* 'u))
(print (parent2 *family-tree2* 'p))
(print (parent2 *family-tree2* 'r))
(print (parent2 *family-tree2* 'e))
(print (parent2 *family-tree2* 'a))
(print (parent2 *family-tree2* nil))
(print (parent2 *family-tree2* 'u))
(print (grandparent2 *family-tree2* 'p))
(print (grandparent2 *family-tree2* 'r))
(print (grandparent2 *family-tree2* 'u))
(print (grandparent2 *family-tree2* 'a))
(print (grandparent2 *family-tree2* 'x))

(terpri)
(princ "**** test-case parents ****")
(terpri)
(princ "**** test-case grandparents ****")

(terpri)
(princ "**** test-case grandparents ****")



