;(load "C:\\WorkSpace\\Artificial Intelligence\\HW1\\3\\test-case.lisp")
(load "C:\\WorkSpace\\Artificial Intelligence\\HW1\\3\\nested-member.lisp")

(terpri)
(princ "**** test-case nested-member ****")
(print (nested-member 'b '(a (b c))))
(print (nested-member 'e '(a (b c))))
(print (nested-member 'b '(a b c)))
(print (nested-member 'b '(a ((b c)))))
(print (nested-member 'a '(((a)) (b c))))
(print (nested-member 'a '(((a d) e) (b c))))
(print (nested-member 'c '(a b ((c)))))
(print (nested-member 'b '((a b) (b c))))
(print (nested-member 'b '()))
(print (nested-member 'b '(a b c ())))
(print (nested-member '(b c) '(a b c)))
(print (nested-member '(b c) '(a (b c))))
(print (nested-member '(b c) '(a ((b c)))))
(print (nested-member '(b c) '((a b) c)))
(terpri)
(princ "**** test-case nested-member ****")

